using MartinGC94.DisplayConfig.Native.Enums;

namespace MartinGC94.DisplayConfig.API
{
    public enum DisplayRotation : uint
    {
        None = DISPLAYCONFIG_ROTATION.DISPLAYCONFIG_ROTATION_IDENTITY,
        Rotate90 = DISPLAYCONFIG_ROTATION.DISPLAYCONFIG_ROTATION_ROTATE90,
        Rotate180 = DISPLAYCONFIG_ROTATION.DISPLAYCONFIG_ROTATION_ROTATE180,
        Rotate270 = DISPLAYCONFIG_ROTATION.DISPLAYCONFIG_ROTATION_ROTATE270
    }
}